name: Debug AWS Key Access

on:
  push:
    branches:
      - main

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Print access key if it exists
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        run: |
          if [ -z "$AWS_ACCESS_KEY_ID" ]; then
            echo "❌ AWS_ACCESS_KEY_ID is NOT available!"
            exit 1
          else
            echo "✅ AWS_ACCESS_KEY_ID is accessible: $AWS_ACCESS_KEY_ID"
          fi
